site_name: Object templates
site_description: The power of components without the complexity.
site_url: https://oot.scaletti.dev
site_author: Juan-Pablo Scaletti
repo_url: https://github.com/jpsca/oot
repo_name: jpsca/oot
copyright: Copyright &copy; 2022 Juan-Pablo Scaletti

nav:
  - Home: index.md
  - Documentation:
    - docs/index.md

theme:
  name: material
  logo: static/img/logo.svg
  favicon: static/img/favicon.svg
  font:
    text: Convergence
    code: Roboto Mono
  custom_dir: overrides
  language: en
  features:
    - navigation.expand
    # - navigation.indexes
    - navigation.instant
    # - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highligh
  icon:
    repo: material/github
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: red
    accent: pink
    toggle:
      icon: octicons/sun-16
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: red
    accent: pink
    toggle:
      icon: octicons/moon-16
      name: Switch to light mode

extra_css:
  - static/css/highlight.css
  # - static/css/termynal.css
  - static/css/common.css
extra_javascript:
  # - static/js/termynal.js
edit_uri: ""
plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - smarty
  - tables
  - toc:
      permalink: "#"
      toc_depth: 4
  - mkautodoc
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
